### ISSUE TITLE
Warning and Critical error codes are inverted

### ISSUE THREAD

**Issue by Yoda-BZH** [nicloay/nginx-icinga-nagios-plugin#1]
Hello

In this piece of code : https://github.com/nicloay/nginx-icinga-nagios-plugin/blob/master/check_nginx#L97-L102 :
```python
   if int(ActiveConn) >= int(critical):
      print 'CRITICAL - %s|%s' % (output,perfdata)
      sys.exit(1)
   elif int(ActiveConn) >= int(warning):
      print 'WARNING - %s|%s' % (output,perfdata)
      sys.exit(2)
```
Critical and Warning exit codes are inverted.

Following https://nagios-plugins.org/doc/guidelines.html#AEN78, `warning` return code should be 1 (not 2) and `critical` return code should be 2 (not 1).

Thank you !

**Comment by nicloay** [comment]
Sorry didn't use this project for a while, but I changed values as you advised. 

Thanks
